name: CWarn (A anticheat plugin)
version: 2.0
main: fr.thet.warn.Main
author: awesomehd1
depend: [ProtocolLib]
commands:
  warndeban:
    description: deban
  log:
    description: log
  warnban:
    description: ban
  ping:
    description: ping
    usage: /ping ou /ping <Joueur>
  warnff:
    description: warnff
    usage: /warnff 
